name: RichNavIndexing
on:
  pull_request:
  push:
    branches:
      - master
      - validate/*

jobs:
  rcn:
    runs-on: windows-latest
    steps:
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
      with: 
        args: git config --global core.longpaths true
    - uses: actions/checkout@v2
    - uses: microsoft/RichCodeNavIndexer@master
      with:
        languages: java
